import { DEFAULT_LAYOUT } from '@/core/constants/default_layout';

export const TEMPLATES_DATA = [
  {
    id: 'bento-saas',
    name: 'Modern SaaS Bento',
    description: 'Header, hero banner, and 3-card feature bento grid layout.',
    category: 'Landing',
    root: DEFAULT_LAYOUT,
  },
  {
    id: 'pricing-table',
    name: 'Pricing Comparison',
    description: '3-tier pricing layout with feature lists and call-to-actions.',
    category: 'Marketing',
    root: {
      id: 'root-pricing',
      name: 'Pricing Page',
      tag: 'div',
      category: 'container',
      styles: {
        display: 'flex',
        flexDirection: 'column',
        width: '100%',
        minHeight: '100%',
        backgroundColor: '#09090b',
        color: '#fafafa',
        paddingTop: '40px',
        paddingRight: '32px',
        paddingBottom: '48px',
        paddingLeft: '32px',
        gap: '32px',
        alignItems: 'center',
      },
      children: [
        {
          id: 'pricing-header',
          name: 'Pricing Header',
          tag: 'div',
          category: 'container',
          styles: {
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            textAlign: 'center',
            gap: '8px',
          },
          children: [
            {
              id: 'price-title',
              name: 'Heading',
              tag: 'h1',
              category: 'typography',
              content: 'Flexible Pricing for Modern Teams',
              styles: { fontSize: '32px', fontWeight: '800', letterSpacing: '-0.5px' },
            },
            {
              id: 'price-sub',
              name: 'Subheading',
              tag: 'p',
              category: 'typography',
              content: 'Scale your layout development with straightforward tiers.',
              styles: { fontSize: '15px', color: '#a1a1aa' },
            },
          ],
        },
        {
          id: 'pricing-grid',
          name: 'Pricing 3-Col Grid',
          tag: 'div',
          category: 'grid',
          styles: {
            display: 'grid',
            gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
            gap: '24px',
            width: '100%',
            maxWidth: '1000px',
          },
          children: [
            {
              id: 'tier-starter',
              name: 'Starter Card',
              tag: 'div',
              category: 'container',
              styles: {
                display: 'flex',
                flexDirection: 'column',
                gap: '16px',
                paddingTop: '28px',
                paddingRight: '24px',
                paddingBottom: '28px',
                paddingLeft: '24px',
                backgroundColor: '#121215',
                borderWidth: '1px',
                borderStyle: 'solid',
                borderColor: '#27272a',
                borderRadius: '16px',
              },
              children: [
                {
                  id: 'tier-1-name',
                  name: 'Tier Name',
                  tag: 'h3',
                  category: 'typography',
                  content: 'Starter',
                  styles: { fontSize: '18px', fontWeight: '700' },
                },
                {
                  id: 'tier-1-price',
                  name: 'Price Tag',
                  tag: 'p',
                  category: 'typography',
                  content: '$0 / month',
                  styles: { fontSize: '28px', fontWeight: '800', color: '#60a5fa' },
                },
                {
                  id: 'tier-1-btn',
                  name: 'Tier Button',
                  tag: 'button',
                  category: 'ui',
                  content: 'Start Free',
                  styles: {
                    paddingTop: '10px',
                    paddingBottom: '10px',
                    backgroundColor: '#27272a',
                    color: '#fafafa',
                    borderRadius: '8px',
                    fontWeight: '600',
                  },
                },
              ],
            },
            {
              id: 'tier-pro',
              name: 'Pro Card (Highlight)',
              tag: 'div',
              category: 'container',
              styles: {
                display: 'flex',
                flexDirection: 'column',
                gap: '16px',
                paddingTop: '28px',
                paddingRight: '24px',
                paddingBottom: '28px',
                paddingLeft: '24px',
                backgroundColor: '#18181b',
                borderWidth: '2px',
                borderStyle: 'solid',
                borderColor: '#3b82f6',
                borderRadius: '16px',
                boxShadow: '0 0 25px rgba(59, 130, 246, 0.25)',
              },
              children: [
                {
                  id: 'tier-2-name',
                  name: 'Tier Name',
                  tag: 'h3',
                  category: 'typography',
                  content: 'Professional',
                  styles: { fontSize: '18px', fontWeight: '700' },
                },
                {
                  id: 'tier-2-price',
                  name: 'Price Tag',
                  tag: 'p',
                  category: 'typography',
                  content: '$29 / month',
                  styles: { fontSize: '28px', fontWeight: '800', color: '#3b82f6' },
                },
                {
                  id: 'tier-2-btn',
                  name: 'Tier Button',
                  tag: 'button',
                  category: 'ui',
                  content: 'Get Started',
                  styles: {
                    paddingTop: '10px',
                    paddingBottom: '10px',
                    backgroundColor: '#3b82f6',
                    color: '#ffffff',
                    borderRadius: '8px',
                    fontWeight: '600',
                  },
                },
              ],
            },
            {
              id: 'tier-enterprise',
              name: 'Enterprise Card',
              tag: 'div',
              category: 'container',
              styles: {
                display: 'flex',
                flexDirection: 'column',
                gap: '16px',
                paddingTop: '28px',
                paddingRight: '24px',
                paddingBottom: '28px',
                paddingLeft: '24px',
                backgroundColor: '#121215',
                borderWidth: '1px',
                borderStyle: 'solid',
                borderColor: '#27272a',
                borderRadius: '16px',
              },
              children: [
                {
                  id: 'tier-3-name',
                  name: 'Tier Name',
                  tag: 'h3',
                  category: 'typography',
                  content: 'Enterprise',
                  styles: { fontSize: '18px', fontWeight: '700' },
                },
                {
                  id: 'tier-3-price',
                  name: 'Price Tag',
                  tag: 'p',
                  category: 'typography',
                  content: '$99 / month',
                  styles: { fontSize: '28px', fontWeight: '800', color: '#10b981' },
                },
                {
                  id: 'tier-3-btn',
                  name: 'Tier Button',
                  tag: 'button',
                  category: 'ui',
                  content: 'Contact Sales',
                  styles: {
                    paddingTop: '10px',
                    paddingBottom: '10px',
                    backgroundColor: '#27272a',
                    color: '#fafafa',
                    borderRadius: '8px',
                    fontWeight: '600',
                  },
                },
              ],
            },
          ],
        },
      ],
    },
  },
  {
    id: 'blank-slate',
    name: 'Blank Canvas',
    description: 'Clean empty container to build your design from scratch.',
    category: 'Starter',
    root: {
      id: 'root-blank',
      name: 'Empty Page',
      tag: 'div',
      category: 'container',
      styles: {
        display: 'flex',
        flexDirection: 'column',
        width: '100%',
        minHeight: '100%',
        backgroundColor: '#09090b',
        color: '#fafafa',
        paddingTop: '32px',
        paddingRight: '32px',
        paddingBottom: '32px',
        paddingLeft: '32px',
        gap: '24px',
      },
      children: [],
    },
  },
];
