export const DEFAULT_LAYOUT = {
  id: 'root-canvas',
  name: 'Canvas Page',
  tag: 'div',
  category: 'container',
  styles: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    minHeight: '100%',
    backgroundColor: '#09090b',
    color: '#fafafa',
    paddingTop: '32px',
    paddingRight: '32px',
    paddingBottom: '48px',
    paddingLeft: '32px',
    gap: '32px',
  },
  children: [
    // Header Navigation
    {
      id: 'navbar-1',
      name: 'Navbar Bar',
      tag: 'header',
      category: 'container',
      styles: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingTop: '16px',
        paddingRight: '24px',
        paddingBottom: '16px',
        paddingLeft: '24px',
        backgroundColor: '#121215',
        borderWidth: '1px',
        borderStyle: 'solid',
        borderColor: '#27272a',
        borderRadius: '12px',
      },
      children: [
        {
          id: 'brand-logo',
          name: 'Brand Logo',
          tag: 'h2',
          category: 'typography',
          content: 'LayoutCraft Studio',
          styles: {
            fontSize: '18px',
            fontWeight: '700',
            color: '#fafafa',
            letterSpacing: '-0.5px',
          },
        },
        {
          id: 'nav-actions',
          name: 'Nav Actions',
          tag: 'div',
          category: 'flex',
          styles: {
            display: 'flex',
            gap: '12px',
            alignItems: 'center',
          },
          children: [
            {
              id: 'badge-pro',
              name: 'Version Badge',
              tag: 'span',
              category: 'ui',
              content: 'v2.4 Ready',
              styles: {
                fontSize: '12px',
                paddingTop: '4px',
                paddingRight: '10px',
                paddingBottom: '4px',
                paddingLeft: '10px',
                backgroundColor: '#1e293b',
                color: '#60a5fa',
                borderRadius: '9999px',
                fontWeight: '600',
              },
            },
            {
              id: 'nav-btn-cta',
              name: 'CTA Button',
              tag: 'button',
              category: 'ui',
              content: 'Get Started',
              styles: {
                fontSize: '14px',
                fontWeight: '600',
                paddingTop: '8px',
                paddingRight: '16px',
                paddingBottom: '8px',
                paddingLeft: '16px',
                backgroundColor: '#3b82f6',
                color: '#ffffff',
                borderRadius: '8px',
                boxShadow: '0 0 15px rgba(59, 130, 246, 0.4)',
              },
            },
          ],
        },
      ],
    },

    // Hero Section
    {
      id: 'hero-section',
      name: 'Hero Section',
      tag: 'section',
      category: 'container',
      styles: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        textAlign: 'center',
        paddingTop: '48px',
        paddingBottom: '48px',
        paddingLeft: '24px',
        paddingRight: '24px',
        gap: '16px',
        backgroundColor: '#121215',
        borderWidth: '1px',
        borderStyle: 'solid',
        borderColor: '#27272a',
        borderRadius: '16px',
      },
      children: [
        {
          id: 'hero-title',
          name: 'Hero Heading',
          tag: 'h1',
          category: 'typography',
          content: 'Visual Frontend Layout Architecture',
          styles: {
            fontSize: '36px',
            fontWeight: '800',
            color: '#fafafa',
            letterSpacing: '-1px',
            maxWidth: '640px',
          },
        },
        {
          id: 'hero-desc',
          name: 'Hero Paragraph',
          tag: 'p',
          category: 'typography',
          content: 'Compose custom grids, flexboxes, and atomic interface elements with real-time property control and instantaneous code export.',
          styles: {
            fontSize: '15px',
            color: '#a1a1aa',
            lineHeight: '1.6',
            maxWidth: '540px',
          },
        },
      ],
    },

    // Bento Grid Section
    {
      id: 'bento-grid',
      name: 'Bento Grid 3-Col',
      tag: 'div',
      category: 'grid',
      styles: {
        display: 'grid',
        gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
        gap: '20px',
        width: '100%',
      },
      children: [
        {
          id: 'card-1',
          name: 'Card Responsive',
          tag: 'div',
          category: 'container',
          styles: {
            display: 'flex',
            flexDirection: 'column',
            gap: '10px',
            paddingTop: '24px',
            paddingRight: '24px',
            paddingBottom: '24px',
            paddingLeft: '24px',
            backgroundColor: '#18181b',
            borderWidth: '1px',
            borderStyle: 'solid',
            borderColor: '#27272a',
            borderRadius: '12px',
          },
          children: [
            {
              id: 'card-1-title',
              name: 'Card Title',
              tag: 'h3',
              category: 'typography',
              content: 'Flex & Grid Engine',
              styles: { fontSize: '18px', fontWeight: '700', color: '#fafafa' },
            },
            {
              id: 'card-1-desc',
              name: 'Card Text',
              tag: 'p',
              category: 'typography',
              content: 'Fine-tune alignment, gaps, directions, and responsive behavior without touching raw CSS.',
              styles: { fontSize: '13px', color: '#a1a1aa', lineHeight: '1.5' },
            },
          ],
        },
        {
          id: 'card-2',
          name: 'Card Tokens',
          tag: 'div',
          category: 'container',
          styles: {
            display: 'flex',
            flexDirection: 'column',
            gap: '10px',
            paddingTop: '24px',
            paddingRight: '24px',
            paddingBottom: '24px',
            paddingLeft: '24px',
            backgroundColor: '#18181b',
            borderWidth: '1px',
            borderStyle: 'solid',
            borderColor: '#27272a',
            borderRadius: '12px',
          },
          children: [
            {
              id: 'card-2-title',
              name: 'Card Title',
              tag: 'h3',
              category: 'typography',
              content: 'Design Token Presets',
              styles: { fontSize: '18px', fontWeight: '700', color: '#fafafa' },
            },
            {
              id: 'card-2-desc',
              name: 'Card Text',
              tag: 'p',
              category: 'typography',
              content: 'Linear dark palettes, precise spacing steps, typography scales, and border radiuses.',
              styles: { fontSize: '13px', color: '#a1a1aa', lineHeight: '1.5' },
            },
          ],
        },
        {
          id: 'card-3',
          name: 'Card Export',
          tag: 'div',
          category: 'container',
          styles: {
            display: 'flex',
            flexDirection: 'column',
            gap: '10px',
            paddingTop: '24px',
            paddingRight: '24px',
            paddingBottom: '24px',
            paddingLeft: '24px',
            backgroundColor: '#18181b',
            borderWidth: '1px',
            borderStyle: 'solid',
            borderColor: '#27272a',
            borderRadius: '12px',
          },
          children: [
            {
              id: 'card-3-title',
              name: 'Card Title',
              tag: 'h3',
              category: 'typography',
              content: 'Clean Code Export',
              styles: { fontSize: '18px', fontWeight: '700', color: '#fafafa' },
            },
            {
              id: 'card-3-desc',
              name: 'Card Text',
              tag: 'p',
              category: 'typography',
              content: 'Export directly to production-grade Tailwind HTML, Vanilla CSS, or React TSX components.',
              styles: { fontSize: '13px', color: '#a1a1aa', lineHeight: '1.5' },
            },
          ],
        },
      ],
    },
  ],
};
