import type { ShortcutItem } from '@/core/types/shortcut.types';

export const SHORTCUTS_DATA: ShortcutItem[] = [
  {
    id: 'copy',
    name: 'Copy Element',
    description: 'Copy selected element to internal and system clipboard',
    keys: ['Ctrl', 'C'],
    category: 'clipboard',
  },
  {
    id: 'cut',
    name: 'Cut Element',
    description: 'Cut selected element and place into clipboard',
    keys: ['Ctrl', 'X'],
    category: 'clipboard',
  },
  {
    id: 'paste',
    name: 'Paste Screenshot / Element',
    description: 'Paste copied element or screenshot image from clipboard onto canvas',
    keys: ['Ctrl', 'V'],
    category: 'clipboard',
  },
  {
    id: 'paste-in-place',
    name: 'Paste In-Place / Plain Text',
    description: 'Paste screenshot, element in-place, or unformatted plain text onto canvas',
    keys: ['Ctrl', 'Shift', 'V'],
    category: 'clipboard',
  },
  {
    id: 'duplicate',
    name: 'Duplicate Element',
    description: 'Create an exact duplicate of the selected element',
    keys: ['Ctrl', 'D'],
    category: 'clipboard',
  },
  {
    id: 'delete',
    name: 'Delete Element',
    description: 'Remove selected element from the canvas hierarchy',
    keys: ['Delete'],
    category: 'clipboard',
  },
  {
    id: 'undo',
    name: 'Undo Action',
    description: 'Revert the last modification on the canvas tree',
    keys: ['Ctrl', 'Z'],
    category: 'canvas',
  },
  {
    id: 'redo',
    name: 'Redo Action',
    description: 'Restore the previously reverted modification',
    keys: ['Ctrl', 'Y'],
    category: 'canvas',
  },
  {
    id: 'move-up',
    name: 'Reorder Element Up',
    description: 'Move current element one position up among its siblings',
    keys: ['Alt', '↑'],
    category: 'canvas',
  },
  {
    id: 'move-down',
    name: 'Reorder Element Down',
    description: 'Move current element one position down among its siblings',
    keys: ['Alt', '↓'],
    category: 'canvas',
  },
  {
    id: 'toggle-visibility',
    name: 'Toggle Visibility',
    description: 'Hide or unhide the selected element on the artboard',
    keys: ['Ctrl', 'H'],
    category: 'canvas',
  },
  {
    id: 'zoom-in',
    name: 'Zoom In Canvas',
    description: 'Increase artboard magnification by 10%',
    keys: ['Ctrl', '+'],
    category: 'navigation',
  },
  {
    id: 'zoom-out',
    name: 'Zoom Out Canvas',
    description: 'Decrease artboard magnification by 10%',
    keys: ['Ctrl', '-'],
    category: 'navigation',
  },
  {
    id: 'zoom-reset',
    name: 'Reset Zoom (100%)',
    description: 'Return canvas zoom magnification to standard 100%',
    keys: ['Ctrl', '0'],
    category: 'navigation',
  },
  {
    id: 'toggle-grid',
    name: 'Toggle Canvas Grid',
    description: 'Toggle alignment dot grid guidelines on and off',
    keys: ['Ctrl', 'G'],
    category: 'navigation',
  },
  {
    id: 'preview-mode',
    name: 'Toggle Live Preview',
    description: 'Switch between editor mode and interactive preview mode',
    keys: ['Ctrl', 'P'],
    category: 'studio',
  },
  {
    id: 'export-code',
    name: 'Export Code Modal',
    description: 'Open the HTML/JSX/JSON multi-format exporter modal',
    keys: ['Ctrl', 'E'],
    category: 'studio',
  },
  {
    id: 'save-session',
    name: 'Quick Save Layout',
    description: 'Acknowledge and save layout state to local session',
    keys: ['Ctrl', 'S'],
    category: 'studio',
  },
  {
    id: 'deselect',
    name: 'Deselect / Close',
    description: 'Clear current element selection or dismiss active modal',
    keys: ['Esc'],
    category: 'studio',
  },
  {
    id: 'help-modal',
    name: 'Keyboard Shortcuts Guide',
    description: 'Display this complete keyboard shortcuts helper panel',
    keys: ['?'],
    category: 'studio',
  },
];
