import { DEFAULT_RESIZABLE_SIDES } from './builder_defaults';

const RAW_TEMPLATES = [
  {
    id: 'saas-landing',
    name: 'SaaS Landing Page',
    category: 'Landing',
    description: 'Header, high-impact hero banner, 3-column features, pricing, CTA, and footer.',
    boxes: [
      {
        name: 'Navigation Header',
        x: 40,
        y: 40,
        width: 1200,
        height: 70,
        color: '#121215',
        borderColor: '#27272a',
        textColor: '#fafafa',
        borderRadius: 8,
        zIndex: 1,
        resizableSides: { ...DEFAULT_RESIZABLE_SIDES },
      },
      {
        name: 'Hero Section & Headline',
        x: 40,
        y: 130,
        width: 1200,
        height: 400,
        color: '#1e3a5f',
        borderColor: '#2563eb',
        textColor: '#93c5fd',
        borderRadius: 12,
        zIndex: 2,
        resizableSides: { ...DEFAULT_RESIZABLE_SIDES },
      },
      {
        name: 'Feature Block 1',
        x: 40,
        y: 550,
        width: 380,
        height: 250,
        color: '#18181b',
        borderColor: '#27272a',
        textColor: '#e4e4e7',
        borderRadius: 8,
        zIndex: 3,
        resizableSides: { ...DEFAULT_RESIZABLE_SIDES },
      },
      {
        name: 'Feature Block 2',
        x: 450,
        y: 550,
        width: 380,
        height: 250,
        color: '#18181b',
        borderColor: '#27272a',
        textColor: '#e4e4e7',
        borderRadius: 8,
        zIndex: 4,
        resizableSides: { ...DEFAULT_RESIZABLE_SIDES },
      },
      {
        name: 'Feature Block 3',
        x: 860,
        y: 550,
        width: 380,
        height: 250,
        color: '#18181b',
        borderColor: '#27272a',
        textColor: '#e4e4e7',
        borderRadius: 8,
        zIndex: 5,
        resizableSides: { ...DEFAULT_RESIZABLE_SIDES },
      },
      {
        name: 'Pricing Plans Matrix',
        x: 40,
        y: 820,
        width: 1200,
        height: 320,
        color: '#312e81',
        borderColor: '#4f46e5',
        textColor: '#c7d2fe',
        borderRadius: 12,
        zIndex: 6,
        resizableSides: { ...DEFAULT_RESIZABLE_SIDES },
      },
      {
        name: 'Call to Action Banner',
        x: 40,
        y: 1160,
        width: 1200,
        height: 180,
        color: '#064e3b',
        borderColor: '#059669',
        textColor: '#a7f3d0',
        borderRadius: 12,
        zIndex: 7,
        resizableSides: { ...DEFAULT_RESIZABLE_SIDES },
      },
      {
        name: 'Footer Section',
        x: 40,
        y: 1360,
        width: 1200,
        height: 110,
        color: '#09090b',
        borderColor: '#27272a',
        textColor: '#a1a1aa',
        borderRadius: 8,
        zIndex: 8,
        resizableSides: { ...DEFAULT_RESIZABLE_SIDES },
      },
    ],
  },
  {
    id: 'analytics-dashboard',
    name: 'Analytics Dashboard',
    category: 'Dashboard',
    description: 'Header, side navigation, KPI stat widgets, primary chart, activity feed, and data table.',
    boxes: [
      {
        name: 'Top Navigation Bar',
        x: 40,
        y: 40,
        width: 1200,
        height: 60,
        color: '#121215',
        borderColor: '#27272a',
        textColor: '#fafafa',
        borderRadius: 8,
        zIndex: 1,
        resizableSides: { ...DEFAULT_RESIZABLE_SIDES },
      },
      {
        name: 'Sidebar Navigation',
        x: 40,
        y: 120,
        width: 240,
        height: 820,
        color: '#121215',
        borderColor: '#27272a',
        textColor: '#e4e4e7',
        borderRadius: 8,
        zIndex: 2,
        resizableSides: { ...DEFAULT_RESIZABLE_SIDES },
      },
      {
        name: 'KPI Metric: Active Users',
        x: 300,
        y: 120,
        width: 290,
        height: 120,
        color: '#18181b',
        borderColor: '#27272a',
        textColor: '#93c5fd',
        borderRadius: 8,
        zIndex: 3,
        resizableSides: { ...DEFAULT_RESIZABLE_SIDES },
      },
      {
        name: 'KPI Metric: Monthly MRR',
        x: 610,
        y: 120,
        width: 290,
        height: 120,
        color: '#18181b',
        borderColor: '#27272a',
        textColor: '#a7f3d0',
        borderRadius: 8,
        zIndex: 4,
        resizableSides: { ...DEFAULT_RESIZABLE_SIDES },
      },
      {
        name: 'KPI Metric: Conversion Rate',
        x: 920,
        y: 120,
        width: 320,
        height: 120,
        color: '#18181b',
        borderColor: '#27272a',
        textColor: '#fde68a',
        borderRadius: 8,
        zIndex: 5,
        resizableSides: { ...DEFAULT_RESIZABLE_SIDES },
      },
      {
        name: 'Main Chart: Revenue Velocity',
        x: 300,
        y: 260,
        width: 600,
        height: 340,
        color: '#1e3a5f',
        borderColor: '#2563eb',
        textColor: '#93c5fd',
        borderRadius: 8,
        zIndex: 6,
        resizableSides: { ...DEFAULT_RESIZABLE_SIDES },
      },
      {
        name: 'Real-time Event Feed',
        x: 920,
        y: 260,
        width: 320,
        height: 340,
        color: '#18181b',
        borderColor: '#27272a',
        textColor: '#e4e4e7',
        borderRadius: 8,
        zIndex: 7,
        resizableSides: { ...DEFAULT_RESIZABLE_SIDES },
      },
      {
        name: 'Data Table: Transactions',
        x: 300,
        y: 620,
        width: 940,
        height: 320,
        color: '#18181b',
        borderColor: '#3f3f46',
        textColor: '#e4e4e7',
        borderRadius: 8,
        zIndex: 8,
        resizableSides: { ...DEFAULT_RESIZABLE_SIDES },
      },
    ],
  },
  {
    id: 'bento-portfolio',
    name: 'Bento Grid Portfolio',
    category: 'Bento',
    description: 'Header, hero intro, project highlights, tech stack pills, and client quotes.',
    boxes: [
      {
        name: 'Portfolio Header',
        x: 40,
        y: 40,
        width: 1200,
        height: 70,
        color: '#121215',
        borderColor: '#27272a',
        textColor: '#fafafa',
        borderRadius: 8,
        zIndex: 1,
        resizableSides: { ...DEFAULT_RESIZABLE_SIDES },
      },
      {
        name: 'Hero Statement Card',
        x: 40,
        y: 130,
        width: 780,
        height: 340,
        color: '#1e3a5f',
        borderColor: '#2563eb',
        textColor: '#93c5fd',
        borderRadius: 12,
        zIndex: 2,
        resizableSides: { ...DEFAULT_RESIZABLE_SIDES },
      },
      {
        name: 'Experience Metric Card',
        x: 840,
        y: 130,
        width: 400,
        height: 340,
        color: '#312e81',
        borderColor: '#4f46e5',
        textColor: '#c7d2fe',
        borderRadius: 12,
        zIndex: 3,
        resizableSides: { ...DEFAULT_RESIZABLE_SIDES },
      },
      {
        name: 'Featured Work: Mobile App',
        x: 40,
        y: 490,
        width: 380,
        height: 340,
        color: '#18181b',
        borderColor: '#27272a',
        textColor: '#e4e4e7',
        borderRadius: 12,
        zIndex: 4,
        resizableSides: { ...DEFAULT_RESIZABLE_SIDES },
      },
      {
        name: 'Featured Work: Web Platform',
        x: 440,
        y: 490,
        width: 380,
        height: 340,
        color: '#18181b',
        borderColor: '#27272a',
        textColor: '#e4e4e7',
        borderRadius: 12,
        zIndex: 5,
        resizableSides: { ...DEFAULT_RESIZABLE_SIDES },
      },
      {
        name: 'Tech Stack & Skills Bento',
        x: 840,
        y: 490,
        width: 400,
        height: 160,
        color: '#064e3b',
        borderColor: '#059669',
        textColor: '#a7f3d0',
        borderRadius: 12,
        zIndex: 6,
        resizableSides: { ...DEFAULT_RESIZABLE_SIDES },
      },
      {
        name: 'Client Testimonial Quote',
        x: 840,
        y: 670,
        width: 400,
        height: 160,
        color: '#451a03',
        borderColor: '#d97706',
        textColor: '#fde68a',
        borderRadius: 12,
        zIndex: 7,
        resizableSides: { ...DEFAULT_RESIZABLE_SIDES },
      },
      {
        name: 'Contact & Social Links',
        x: 40,
        y: 850,
        width: 1200,
        height: 120,
        color: '#121215',
        borderColor: '#27272a',
        textColor: '#a1a1aa',
        borderRadius: 8,
        zIndex: 8,
        resizableSides: { ...DEFAULT_RESIZABLE_SIDES },
      },
    ],
  },
  {
    id: 'editorial-magazine',
    name: 'Editorial Magazine',
    category: 'Editorial',
    description: 'Publication header, lead cover story, trending sidebar, story grid, and newsletter.',
    boxes: [
      {
        name: 'Publication Masthead',
        x: 40,
        y: 40,
        width: 1200,
        height: 80,
        color: '#121215',
        borderColor: '#27272a',
        textColor: '#fafafa',
        borderRadius: 8,
        zIndex: 1,
        resizableSides: { ...DEFAULT_RESIZABLE_SIDES },
      },
      {
        name: 'Lead Cover Story',
        x: 40,
        y: 140,
        width: 780,
        height: 420,
        color: '#3b0764',
        borderColor: '#7c3aed',
        textColor: '#e9d5ff',
        borderRadius: 10,
        zIndex: 2,
        resizableSides: { ...DEFAULT_RESIZABLE_SIDES },
      },
      {
        name: 'Trending Articles Sidebar',
        x: 840,
        y: 140,
        width: 400,
        height: 420,
        color: '#18181b',
        borderColor: '#27272a',
        textColor: '#e4e4e7',
        borderRadius: 10,
        zIndex: 3,
        resizableSides: { ...DEFAULT_RESIZABLE_SIDES },
      },
      {
        name: 'Category Story 1',
        x: 40,
        y: 580,
        width: 380,
        height: 260,
        color: '#18181b',
        borderColor: '#27272a',
        textColor: '#e4e4e7',
        borderRadius: 8,
        zIndex: 4,
        resizableSides: { ...DEFAULT_RESIZABLE_SIDES },
      },
      {
        name: 'Category Story 2',
        x: 440,
        y: 580,
        width: 380,
        height: 260,
        color: '#18181b',
        borderColor: '#27272a',
        textColor: '#e4e4e7',
        borderRadius: 8,
        zIndex: 5,
        resizableSides: { ...DEFAULT_RESIZABLE_SIDES },
      },
      {
        name: 'Category Story 3',
        x: 840,
        y: 580,
        width: 400,
        height: 260,
        color: '#18181b',
        borderColor: '#27272a',
        textColor: '#e4e4e7',
        borderRadius: 8,
        zIndex: 6,
        resizableSides: { ...DEFAULT_RESIZABLE_SIDES },
      },
      {
        name: 'Newsletter Subscription',
        x: 40,
        y: 860,
        width: 1200,
        height: 160,
        color: '#1e3a5f',
        borderColor: '#2563eb',
        textColor: '#93c5fd',
        borderRadius: 10,
        zIndex: 7,
        resizableSides: { ...DEFAULT_RESIZABLE_SIDES },
      },
      {
        name: 'Editorial Footer',
        x: 40,
        y: 1040,
        width: 1200,
        height: 100,
        color: '#09090b',
        borderColor: '#27272a',
        textColor: '#a1a1aa',
        borderRadius: 8,
        zIndex: 8,
        resizableSides: { ...DEFAULT_RESIZABLE_SIDES },
      },
    ],
  },
  {
    id: 'mobile-app-wireframe',
    name: 'Mobile Multi-Screen Flow',
    category: 'Mobile',
    description: 'Three mobile screen frames (Onboarding, Feed, Profile) for responsive app wireframing.',
    boxes: [
      {
        name: 'Flow Label & Spec Notes',
        x: 40,
        y: 40,
        width: 1200,
        height: 50,
        color: '#121215',
        borderColor: '#27272a',
        textColor: '#93c5fd',
        borderRadius: 8,
        zIndex: 1,
        resizableSides: { ...DEFAULT_RESIZABLE_SIDES },
      },
      {
        name: 'Screen 1: Welcome & Onboarding',
        x: 60,
        y: 110,
        width: 360,
        height: 640,
        color: '#18181b',
        borderColor: '#3f3f46',
        textColor: '#fafafa',
        borderRadius: 24,
        zIndex: 2,
        resizableSides: { ...DEFAULT_RESIZABLE_SIDES },
      },
      {
        name: 'Screen 2: Feed & Explore',
        x: 460,
        y: 110,
        width: 360,
        height: 640,
        color: '#1e3a5f',
        borderColor: '#2563eb',
        textColor: '#93c5fd',
        borderRadius: 24,
        zIndex: 3,
        resizableSides: { ...DEFAULT_RESIZABLE_SIDES },
      },
      {
        name: 'Screen 3: Settings & Profile',
        x: 860,
        y: 110,
        width: 360,
        height: 640,
        color: '#312e81',
        borderColor: '#4f46e5',
        textColor: '#c7d2fe',
        borderRadius: 24,
        zIndex: 4,
        resizableSides: { ...DEFAULT_RESIZABLE_SIDES },
      },
    ],
  },
];

export const BUILDER_TEMPLATES = RAW_TEMPLATES.map((template) => ({
  ...template,
  boxes: template.boxes.map((box, idx) => ({
    ...box,
    id: box.id || `${template.id}-box-${idx + 1}`,
  })),
}));
